CONSENT_VERSION = "2026-07-08.1"
PRIVACY_VERSION = "2026-07-08.1"
COOKIE_TEXT_VERSION = "2026-07-08.1"
FILE_RETENTION_DAYS = 30

COOKIE_ACCEPTED = "accepted"
COOKIE_REJECTED = "rejected"
COOKIE_CHOICES = {COOKIE_ACCEPTED, COOKIE_REJECTED}

COMPLIANCE_CONTEXT = {
    "CONSENT_VERSION": CONSENT_VERSION,
    "PRIVACY_VERSION": PRIVACY_VERSION,
    "COOKIE_TEXT_VERSION": COOKIE_TEXT_VERSION,
    "FILE_RETENTION_DAYS": FILE_RETENTION_DAYS,
}
