# Generated by Django 6.0.6 on 2026-07-06 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('logo', models.CharField(blank=True, max_length=300)),
                ('logo_source_url', models.URLField(blank=True, max_length=800)),
                ('official_site', models.URLField(blank=True, max_length=500)),
                ('category', models.CharField(blank=True, max_length=220)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('show_on_home', models.BooleanField(default=False)),
                ('show_on_partners', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('name', models.CharField(max_length=220)),
                ('official_site', models.URLField(blank=True, max_length=500)),
                ('logo', models.CharField(blank=True, max_length=300)),
                ('logo_source_url', models.URLField(blank=True, max_length=800)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('confidence', models.CharField(blank=True, max_length=120)),
                ('source', models.CharField(blank=True, max_length=220)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('purpose', models.TextField(blank=True)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directions', to='main.catalogblock')),
            ],
            options={
                'ordering': ['block__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CatalogSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='main.direction')),
            ],
            options={
                'ordering': ['direction__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=220)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('crm_category', models.CharField(blank=True, max_length=180)),
                ('crm_comment_hint', models.TextField(blank=True)),
                ('ai_aliases', models.JSONField(blank=True, default=list)),
                ('ai_must_ask', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_groups', to='main.catalogsystem')),
            ],
            options={
                'ordering': ['system__sort_order', 'sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VendorProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show_in_catalog', models.BooleanField(default=True)),
                ('show_in_vendors', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=False)),
                ('show_in_partners', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, max_length=80)),
                ('confidence', models.CharField(blank=True, max_length=120)),
                ('matched_by', models.CharField(blank=True, max_length=220)),
                ('source', models.CharField(blank=True, max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.productgroup')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vendor')),
            ],
            options={
                'ordering': ['product_group__title', 'vendor__name'],
                'unique_together': {('vendor', 'product_group')},
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='product_groups',
            field=models.ManyToManyField(related_name='vendors', through='main.VendorProductGroup', to='main.productgroup'),
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='main.productgroup')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'unique_together': {('product_group', 'title')},
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=220)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('product_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='main.productgroup')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
                'unique_together': {('product_group', 'title')},
            },
        ),
    ]
