# Generated by Django 6.0.6 on 2026-07-07 07:53

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('catalog_mini', 'Мини-заявка каталога'), ('catalog_request', 'Заявка каталога'), ('contact', 'Контактная форма'), ('ai_chat', 'AI-чат')], default='catalog_mini', max_length=40)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('sent_to_bitrix', 'Передана в Bitrix'), ('failed', 'Ошибка передачи'), ('closed', 'Закрыта')], default='new', max_length=40)),
                ('contact_name', models.CharField(blank=True, max_length=220)),
                ('phone', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.CharField(blank=True, max_length=220)),
                ('message', models.TextField(blank=True)),
                ('request_text', models.TextField(blank=True)),
                ('consent', models.BooleanField(default=False)),
                ('catalog_path', models.CharField(blank=True, max_length=700)),
                ('bitrix_lead_id', models.CharField(blank=True, max_length=120)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='main.productgroup')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('system_title', models.CharField(blank=True, max_length=220)),
                ('product_group_title', models.CharField(max_length=220)),
                ('product_type_title', models.CharField(blank=True, max_length=220)),
                ('quantity', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('raw_item', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.lead')),
                ('product_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_items', to='main.productgroup')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_items', to='main.producttype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=main.models.lead_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='main.lead')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
