# Generated by Django 6.0.6 on 2026-07-08 12:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_lead_leaditem_uploadedfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('consent_version', models.CharField(max_length=80)),
                ('privacy_version', models.CharField(max_length=80)),
                ('cookie_text_version', models.CharField(max_length=80)),
                ('choice', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_url', models.URLField(blank=True, max_length=1200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('form_type', models.CharField(max_length=80)),
                ('consent_version', models.CharField(max_length=80)),
                ('privacy_version', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_url', models.URLField(blank=True, max_length=1200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('checkbox_value', models.BooleanField(default=False)),
                ('file_upload_fact', models.BooleanField(default=False)),
                ('submitted_fields_hash', models.CharField(blank=True, max_length=64)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to='main.lead')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
