# Generated by Django 6.0.6 on 2026-07-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lead_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='category',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='lead',
            name='direction',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='lead',
            name='object_name',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
