# Generated by Django 6.0.6 on 2026-07-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_profile_company_name_profile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
