# Generated by Django 6.0.6 on 2026-07-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_lead_user_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('catalog_mini', 'Мини-заявка каталога'), ('catalog_request', 'Заявка каталога'), ('contact', 'Контактная форма'), ('ai_chat', 'AI-чат'), ('cooperation', 'Предложение о сотрудничестве')], default='catalog_mini', max_length=40),
        ),
    ]
