# Generated by Django 5.2 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_alter_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="field_name",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
